### ISSUE TITLE
Training data for the model

### ISSUE THREAD

**Issue by epoc88** [LaggyHammer/real-time-OCR#2]
I wondered how did you train the model frozen_east_text_detection.pb.
Is it an object detector that trained from labelled bounding box images?

**Comment by LaggyHammer** [comment]
@epoc88 so the text detection model came from this [paper](https://arxiv.org/pdf/1704.03155.pdf).  
They have trained, tested & benchmarked the model with ICDAR 2015, COCO-Text and MSRA-TD500 datasets. You can find more info in section 4.1 of the paper.
